### PR TITLE
Enabling json logging

### PR DESCRIPTION
**Pull request by mobasherul**

### CODE REVIEW

**Comment by akomakom** [comment]
I started moving terracotta-cloud to v4-enterprise (see PR 53) for docker from source.

Could we do this on top after it's merged?

**Comment by mobasherul** [comment]
> I started moving terracotta-cloud to v4-enterprise (see PR 53) for docker from source.
> 
> Could we do this on top after it's merged?

Yes I guess we can its anyway not complete

**Comment by mathieucarbou** [comment]
> I started moving terracotta-cloud to v4-enterprise (see PR 53) for docker from source.
> 
> Could we do this on top after it's merged?

Thanks!

Quick question about https://github.softwareag.com/Terracotta/v4-enterprise/pull/53: your daggy PR will also be able to go in branch 4.3.10 ? And the 4.4.0 branch here matches main in v4-enterprise ?

**Comment by mathieucarbou** [comment]
No need to review - this PR has to be closed and will be moved on top of 53.

**Pull request closed without merging**
